### ISSUE TITLE
Makefile missing

### ISSUE THREAD

**Issue by michaelaye** [scipy-lectures/scipy-lectures.github.com#4]
the build instruction says:

type `make html` to build the html output, but there is no Makefule in the repo, therefore make returns with the error 

make: **\* No rule to make target `html'.  Stop.

**Comment by pdebuyl** [comment]
Hi, this repository is just used to publish the web pages of the lectures. Visit https://github.com/scipy-lectures/scipy-lecture-notes for the actual code. There, you will find a Makefile.

Regards,

Pierre

@GaelVaroquaux can you close this?

**Comment by GaelVaroquaux** [comment]
@pdebuyl : I can make you core dev if you want.

**Comment by pdebuyl** [comment]
Gladly :-)
